apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-dep
  labels:
    app: shipping-dep
    tier: backend-dep
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        app: shipping
        tier: backend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: jagadevops321/shipping:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: shipping  

---


apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
