apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dep
  namespace: roboshop
  labels:
    app: mongodb-dep
    tier: database-dep
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        app: mongodb
        tier: database                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
         app: mongodb
         tier: database
    spec:
      containers:
      - name: mongodb
        image: jagadevops321/mongodb:1.0.0
        imagePullPolicy: Always

---


apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: roboshop
spec:
	selector:
      app: mongodb
      tier: database
	ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
