apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO: true

  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-dep
  namespace: roboshop
  labels:
    app: catalogue-dep
    tier: backend-dep
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        app: catalogue
        tier: backend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: jagadevops321/catalogue:1.0.0
        imagePullPolicy: Always
        envFrom:
	      - configMapRef:
            name: catalogue  

---


apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
spec:
	selector:
    app: catalogue
    tier: backend
	ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
