apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"

  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dep
  labels:
    app: user-dep
    tier: backend-dep
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        app: user
        tier: backend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: user
        tier: backend
    spec:
      containers:
      - name: user
        image: jagadevops321/user:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: user  

---


apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
