# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: catalogue
#   namespace: roboshop
# data:
#   MONGO: "true"

  

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  labels:
    app: web-dep
    tier: frontend-dep
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
        app: web
        tier: frontend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: web
        tier: frontend 
    spec:
      containers:
      - name: web
        image: jagadevops321/web:1.0.0
        imagePullPolicy: Always
        # envFrom:
        # - configMapRef:
        #    name: catalogue  

---


apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
